name: Update submodules
on:
  repository_dispatch:
    types: [update-submodule]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodules
        run: |
          git submodule update --init --recursive -f --remote -- "${{ github.event.client_payload.module }}"
          git config --global user.name "Github Actions"
          git config --global user.email "noreply@github.com"
          git commit -am "👽 Update submodule ${{ github.event.client_payload.module }} to ${{ github.event.client_payload.sha }}"
          git push
      - name: Trigger re-build
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: submodules-updated
          repository: "${{ github.repository }}"
